# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# https://www.youtube.com/watch?v=yRz8D_oJMWQ

name: page

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  cache-and-install:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x ]
        os: [ ubuntu-latest]
        experimental: [ true ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: fix resource path
        run: |
          ls && pwd
          run: sed -i "s|/assets/index|/RainWarn/assets/index-|g" dist/index.html
      # - name: MoveFile
      #   run: |
      #     mkdir docu
      #     mv build docu/build 
      # https://github.com/marketplace/actions/deploy-to-github-pages
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist